[package]
name = "http_core"
version = "0.1.0"
edition = "2021"

[dependencies]
auth = { path = "../auth" }
bytes = "1.7.1"
http-body-util = "0.1.2"
hyper = "1.4.1"
serde = "1.0.206"
serde_json = "1.0.124"
