[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
base64 = "0.22.1"
hmac = "0.12.1"
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
sha2 = "0.10.8"
tracing = "0.1.40"
types = { path = "../types" }
