[package]
name = "derives"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
sqlx = { version = "0.8.0", features = ["postgres"] }
syn = "2.0.74"
